baseURL = 'https://isaacdnew.github.io'
languageCode = 'en-us'
title = 'Isaac Newcomb'

theme = "aether"

[params]
	brand = "isaacdnew"
	description = "My personal website and portfolio"
  github = "https://github.com/isaacdnew"
  linkedin = "https://www.linkedin.com/in/isaacdnew/"
	bgimg = "Path, within the 'assets' folder, of the image used for the page background - optional"
	rssinmenu = false
	headshotimg = "img/isaac-holding-melodica-square.jpg"

[markup]
  [markup.highlight]
    style = "igor"